name: phone_test_task
description: Solution for Intern Flutter Developer test task
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  modal_bottom_sheet:
    git:
      url: https://github.com/eli1stark/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.4
  mask_text_input_formatter: ^2.4.0
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/arrow_right.svg
    - assets/cross_icon.svg
    - assets/search_icon.svg

  uses-material-design: true
